name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Value
      id: value
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Value
        setup-command: cd src/main/grammar && java -jar ../../../utilities/antlr-4.13.1-complete.jar
          SimpleLang.g4 && javac -cp ../../../utilities/antlr-4.13.1-complete.jar
          SimpleLang*.java
        command: cd src/main/grammar && java -cp ../../../utilities/antlr-4.13.1-complete.jar:.
          org.antlr.v4.gui.TestRig SimpleLang simplelang
        input: |-
          void main()
          {
              int a = -1;
              int b=2,c=3;
              int *d = &a;

              char e = 'a';
              char f[] = "abc";

              float g = 1.0;
              double h = 2.45;

              int a3[] = {1, 2, 3, 4, 5};
              int a4[][] = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};
              int (*pa2)[] = {1, 2, 3, 4, 5};

              const long long int **const*const x[5];
          }
        expected-output: '1'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        VALUE_RESULTS: "${{steps.value.outputs.result}}"
      with:
        runners: value
